services:
  nginx:
    healthcheck:
      test: 'curl --fail 127.0.0.1:80'
    depends_on:
      php-fpm:
        condition: service_started

  php-fpm:
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy

  mysql:
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 30

  postgres:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 30
